[package]
name = "aoc2023_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.3"
ndarray = "0.15.6"
rand = "0.8.5"
rmpfit = "0.1.0"