# eglot uses the repo root as the project root. rust-analyzer only analyzes files/projects it finds via Cargo.toml in the project root. So this is the hack.

[workspace]
resolver = "2"
members = ["2020", "2023"]
